version: '3.5'
services:
  web_dev:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
    environment:
      - ENV=development
      - PORT=4000
      - DB=mongodb://mongodb:27017/saerch-and-bookmark
      - SECRET='search-and-bookmark-app'
  mongodb:
    image: mongo:latest
    container_name: "mongodb2"
    environment: 
      - MONGO_DATA_DIR=/usr/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/usr/data/db
    ports:
        - 27018:27018
    command: mongod --smallfiles --logpath=/dev/null
networks:
  default:
    name: web_dev
